### ISSUE TITLE
change csv delimiter from ; to ,

### ISSUE THREAD

**Issue by cg-cnu** [openMVG/CameraSensorSizeDatabase#13]
Hi there,

The current csv files use `;` as the delimiter. Generally `,` is the default delimiter accepted in lot of places and would be helpful to use this csv files in other applications. Apart from that github also helps you render them beautifully in the webpage with search option if its delimited by `,`.

Delimited by `,` 
![image](https://user-images.githubusercontent.com/2767425/41890289-8901b3a0-792c-11e8-8841-e29f2c235107.png)

Delimited by `;`
![image](https://user-images.githubusercontent.com/2767425/41890427-1553bccc-792d-11e8-89d3-c93c4f710479.png)

Would be happy to do a pr if approved.

**Comment by pmoulon** [comment]
Hi,
Sure, feel free to make a PR for both of the csv file ;-)

**Comment by zoomx** [comment]
CSV can be delimited by ; it depends on your windows or program settings. My settings uses ; for the same reasone expressed here
[https://stackoverflow.com/questions/10140999/csv-with-comma-or-semicolon](url)

**Comment by daz** [comment]
Great point about GitHub rendering, this would be cool to see.
