### ISSUE TITLE
sensor_database.csv file is read only

### ISSUE THREAD

**Issue by yungmags** [openMVG/CameraSensorSizeDatabase#6]
Hi! I'm having a small issue trying to add my camera to the database. I have an editor that supports Unix line endings; it's just that when I try to open the sensor_database.csv file, it says read-only and it won't allow me to change the permissions on the document. I have to make a duplicate of the file to change the document, but it also won't allow me to replace the original document with my edited one. I'm working on a Mac. Does anyone have any suggestions?

**Comment by pmoulon** [comment]
If you want using it for OpenMVG purpose you must consider to use https://github.com/openMVG/openMVG/blob/master/src/openMVG/exif/sensor_width_database/sensor_width_camera_database.txt

I think this is the default behavior of Office to open new file in ReadOnlyMode. Often you have a change permissions on the top that is displayed when you attempt to modify the document.
